version: "3.3"

services:
  mysql:
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./deploy/docker/mysql:/docker-entrypoint-initdb.d

  adminer:
    restart: always
    ports:
      - 8882:8080

  redis:
    restart: always
    ports:
      - "6379:6379"

  redis-commander:
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      # - HTTP_USER=root
      # - HTTP_PASSWORD=root
    ports:
      - "8081:8081"

  loki:
    ports:
      - "3100:3100"
    volumes:
      - loki:/loki
      - "./deploy/docker/loki/config.yaml:/etc/loki/config.yaml"
    command: -config.file=/etc/loki/config.yaml

  grafana:
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=root
      # - GF_SERVER_SERVE_FROM_SUB_PATH=true
      # - GF_SERVER_ROOT_URL=http://domain.com/grafana
    ports:
      - "3333:3000"

  api:
    environment:
      - CONFIG=docker
      - PORT=80
    ports:
      - "9487:80"

volumes:
  mysql:
  loki:
