version: "3.3"
services:
  mysql:
    image: mysql:8.0.21

  adminer:
    image: adminer:latest
    depends_on:
      - mysql

  redis:
    image: redis:6.2

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis

  loki:
    image: grafana/loki

  grafana:
    image: grafana/grafana
    depends_on:
      - loki

  api:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    depends_on:
      - mysql
      - redis
