apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: default
type: Opaque
data:
  # root
  # in base64
  GF_SECURITY_ADMIN_USER: cm9vdA==
  # root
  # in base64
  GF_SECURITY_ADMIN_PASSWORD: cm9vdA==
