// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/logic/badminton/team.go

// Package badminton is a generated GoMock package.
package badminton

import (
	redis "heroku-line-bot/src/model/redis"
	error "heroku-line-bot/src/pkg/util/error"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIBadmintonTeamLogic is a mock of IBadmintonTeamLogic interface.
type MockIBadmintonTeamLogic struct {
	ctrl     *gomock.Controller
	recorder *MockIBadmintonTeamLogicMockRecorder
}

// MockIBadmintonTeamLogicMockRecorder is the mock recorder for MockIBadmintonTeamLogic.
type MockIBadmintonTeamLogicMockRecorder struct {
	mock *MockIBadmintonTeamLogic
}

// NewMockIBadmintonTeamLogic creates a new mock instance.
func NewMockIBadmintonTeamLogic(ctrl *gomock.Controller) *MockIBadmintonTeamLogic {
	mock := &MockIBadmintonTeamLogic{ctrl: ctrl}
	mock.recorder = &MockIBadmintonTeamLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBadmintonTeamLogic) EXPECT() *MockIBadmintonTeamLogicMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockIBadmintonTeamLogic) Load(ids ...uint) (map[uint]*redis.ClubBadmintonTeam, error.IError) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Load", varargs...)
	ret0, _ := ret[0].(map[uint]*redis.ClubBadmintonTeam)
	ret1, _ := ret[1].(error.IError)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockIBadmintonTeamLogicMockRecorder) Load(ids ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockIBadmintonTeamLogic)(nil).Load), ids...)
}
