kind: Service
apiVersion: v1
metadata:
  name: line-bot
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: client
  selector:
    app: line-bot

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: line-bot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: line-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: line-bot
    spec:
      containers:
        - name: line-bot
          image: line-bot
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64M"
              cpu: "100m"
            limits:
              memory: "512M"
              cpu: "1.5"
          env:
            - name: CONFIG
              value: "k8s"
            - name: PORT
              value: "80"
          ports:
            - name: client
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/config
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: line-bot
