kind: Service
apiVersion: v1
metadata:
  name: line-bot
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: client
  selector:
    app: line-bot

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: line-bot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: line-bot
  strategy:
    rollingUpdate:
      # 升級時最多會先建立的 pod
      maxSurge: 1
      # 升級時最多能關閉的 pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  template:
    metadata:
      labels:
        app: line-bot
    spec:
      containers:
        - name: line-bot
          image: line-bot
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32M"
              cpu: "50m"
            limits:
              memory: "256M"
              cpu: "150m"
          env:
            - name: CONFIG
              value: "k8s"
            - name: PORT
              value: "80"
          ports:
            - name: client
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/config
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: line-bot
