apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app
spec:
  secretName: letsencrypt-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - domain.com
