var:
  use_debug: true

server:
  host: "0.0.0.0"
  port: 80

line_bot:
  message_bot:
    admin_id: "admin line id"
    channel_access_token: "access token"
  line_login_channel_id: 123

telegram_bot:
  admin_id: 123
  channel_access_token: "access token"

badminton:
  liff_url: "line login"
  club_team_id: 1

google_script:
  url: "https://script.google.com/macros/s/google script/exec"

loki:
  url: "http://localhost:3100"

backgrounds:
  activity_creator:
    spec: "0 0 9 * * *"
    period_type: 3

db:
  max_idle_conns: 5
  max_open_conns: 10
  max_life_hour: 1

club_db:
  protocol: "postgre"
  server:
    host: "localhost"
    port: 5432
  database: "club"
  user: "root"
  password: "root"
  param: "sslmode=prefer"

redis:
  max_life_hour: 1

club_redis:
  protocol: "redis"
  server:
    host: "localhost"
    port: 6379
  database: "0"
  password: ""
