var:
  use_debug: true
  log_dir: ""
  # default Asia/Taipei
  time_zone: "Asia/Taipei"

server:
  host: "0.0.0.0"
  port: 80

line_bot:
  message_bot:
    # admin line id
    admin_id: ""
    # access token
    channel_access_token: ""
  line_login_channel_id: 0

telegram_bot:
  admin_id: 0
  # access token
  channel_access_token: ""

badminton:
  # line login url
  liff_url: ""
  club_team_id: 1

google_script:
  # example https://script.google.com/macros/s/<google script>/exec
  url: ""

loki:
  url: "http://localhost:3100"

backgrounds:
  activity_creator:
    spec: "0 0 9 * * *"
    period_type: 3

db:
  max_idle_conns: 5
  max_open_conns: 10
  max_life_hour: 1

club_db:
  protocol: "mysql"
  server:
    host: "localhost"
    port: 3306
  database: "club"
  user: "root"
  password: "root"
  param: "charset=utf8&parseTime=True&loc=Asia%2FTaipei&readTimeout=5s"

redis:
  max_life_hour: 1

club_redis:
  protocol: "redis"
  server:
    host: "localhost"
    port: 6379
  database: "0"
  password: ""
