apiVersion: v1
kind: Secret
metadata:
  name: redis-commander
  namespace: default
type: Opaque
data:
  # no auth
  # in base64
  HTTP_USER: ""
  # no auth
  # in base64
  HTTP_PASSWORD: ""
  # label:hostname:port:dbIndex:password
  # local:redis:6379
  # in base64
  REDIS_HOSTS: bG9jYWw6cmVkaXM6NjM3OQ==
