// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/badminton/rental-courts": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "新增租場",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Badminton"
                ],
                "summary": "新增租場",
                "parameters": [
                    {
                        "description": "參數",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqs.AddRentalCourt"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "資料",
                        "schema": {
                            "$ref": "#/definitions/resp.Base"
                        }
                    }
                }
            }
        },
        "/club/rental-courts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "租場狀況",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Club"
                ],
                "summary": "租場狀況",
                "parameters": [
                    {
                        "type": "string",
                        "default": "2013-08-02T00:00:00+08:00",
                        "description": "起始日期",
                        "name": "from_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "2013-08-02T00:00:00+08:00",
                        "description": "結束日期",
                        "name": "to_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "資料",
                        "schema": {
                            "$ref": "#/definitions/resp.GetRentalCourts"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "reqs.AddRentalCourt": {
            "type": "object",
            "required": [
                "court_count",
                "court_from_time",
                "court_to_time",
                "from_date",
                "place_id",
                "price_per_hour",
                "to_date"
            ],
            "properties": {
                "balance_date": {
                    "type": "string"
                },
                "balance_money": {
                    "type": "integer"
                },
                "court_count": {
                    "type": "integer"
                },
                "court_from_time": {
                    "type": "string"
                },
                "court_to_time": {
                    "type": "string"
                },
                "desposit_date": {
                    "type": "string"
                },
                "desposit_money": {
                    "type": "integer"
                },
                "every_weekday": {
                    "type": "integer"
                },
                "exclude_dates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "from_date": {
                    "type": "string",
                    "default": "2013-08-02T00:00:00+08:00"
                },
                "place_id": {
                    "type": "integer"
                },
                "price_per_hour": {
                    "type": "integer"
                },
                "to_date": {
                    "type": "string",
                    "default": "2013-08-02T00:00:00+08:00"
                }
            }
        },
        "resp.Base": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "resp.GetRentalCourts": {
            "type": "object",
            "properties": {
                "not_pay_day_courts": {
                    "$ref": "#/definitions/resp.GetRentalCourtsPayInfo"
                },
                "not_refund_day_courts": {
                    "$ref": "#/definitions/resp.GetRentalCourtsPayInfo"
                },
                "total_day_courts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resp.GetRentalCourtsDayCourts"
                    }
                }
            }
        },
        "resp.GetRentalCourtsCourtInfo": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                },
                "from_time": {
                    "type": "string"
                },
                "place": {
                    "type": "string"
                },
                "to_time": {
                    "type": "string"
                }
            }
        },
        "resp.GetRentalCourtsDayCourts": {
            "type": "object",
            "properties": {
                "courts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resp.GetRentalCourtsDayCourtsInfo"
                    }
                },
                "date": {
                    "type": "string"
                },
                "is_multiple_place": {
                    "type": "boolean"
                }
            }
        },
        "resp.GetRentalCourtsDayCourtsInfo": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                },
                "from_time": {
                    "type": "string"
                },
                "place": {
                    "type": "string"
                },
                "reason_message": {
                    "type": "string"
                },
                "refund_time": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "to_time": {
                    "type": "string"
                }
            }
        },
        "resp.GetRentalCourtsPayInfo": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "number"
                },
                "courts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resp.GetRentalCourtsPayInfoDay"
                    }
                }
            }
        },
        "resp.GetRentalCourtsPayInfoDay": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "number"
                },
                "courts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resp.GetRentalCourtsCourtInfo"
                    }
                },
                "date": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api/",
	Schemes:     []string{},
	Title:       "Heroku-Line-Bot",
	Description: "Line-Bot",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
