basePath: /api/
definitions:
  reqs.AddRentalCourt:
    properties:
      balance_date:
        type: string
      balance_money:
        type: integer
      court_count:
        type: integer
      court_from_time:
        type: string
      court_to_time:
        type: string
      desposit_date:
        type: string
      desposit_money:
        type: integer
      every_weekday:
        type: integer
      exclude_dates:
        items:
          type: string
        type: array
      from_date:
        default: "2013-08-02T00:00:00+08:00"
        type: string
      place_id:
        type: integer
      price_per_hour:
        type: integer
      team_id:
        type: integer
      to_date:
        default: "2013-08-02T00:00:00+08:00"
        type: string
    required:
    - court_count
    - court_from_time
    - court_to_time
    - from_date
    - place_id
    - price_per_hour
    - team_id
    - to_date
    type: object
  resp.Base:
    properties:
      data: {}
      message:
        type: string
    type: object
  resp.GetActivitys:
    properties:
      activitys:
        items:
          $ref: '#/definitions/resp.GetActivitysActivity'
        type: array
      data_count:
        type: integer
    type: object
  resp.GetActivitysActivity:
    properties:
      activity_id:
        type: integer
      courts:
        items:
          $ref: '#/definitions/resp.GetActivitysCourt'
        type: array
      date:
        type: string
      description:
        type: string
      is_show_members:
        type: boolean
      members:
        items:
          $ref: '#/definitions/resp.GetActivitysMember'
        type: array
      people_limit:
        type: integer
      place_id:
        type: integer
      place_name:
        type: string
      price:
        type: integer
      team_id:
        type: integer
      team_name:
        type: string
    type: object
  resp.GetActivitysCourt:
    properties:
      count:
        type: integer
      from_time:
        type: string
      to_time:
        type: string
    type: object
  resp.GetActivitysMember:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  resp.GetRentalCourts:
    properties:
      not_pay_day_courts:
        $ref: '#/definitions/resp.GetRentalCourtsPayInfo'
      not_refund_day_courts:
        $ref: '#/definitions/resp.GetRentalCourtsPayInfo'
      total_day_courts:
        items:
          $ref: '#/definitions/resp.GetRentalCourtsDayCourts'
        type: array
    type: object
  resp.GetRentalCourtsCourtInfo:
    properties:
      cost:
        type: number
      count:
        type: integer
      from_time:
        type: string
      place:
        type: string
      to_time:
        type: string
    type: object
  resp.GetRentalCourtsDayCourts:
    properties:
      courts:
        items:
          $ref: '#/definitions/resp.GetRentalCourtsDayCourtsInfo'
        type: array
      date:
        type: string
      is_multiple_place:
        type: boolean
    type: object
  resp.GetRentalCourtsDayCourtsInfo:
    properties:
      cost:
        type: number
      count:
        type: integer
      from_time:
        type: string
      place:
        type: string
      reason_message:
        type: string
      refund_time:
        type: string
      status:
        type: integer
      to_time:
        type: string
    type: object
  resp.GetRentalCourtsPayInfo:
    properties:
      cost:
        type: number
      courts:
        items:
          $ref: '#/definitions/resp.GetRentalCourtsPayInfoDay'
        type: array
    type: object
  resp.GetRentalCourtsPayInfoDay:
    properties:
      cost:
        type: number
      courts:
        items:
          $ref: '#/definitions/resp.GetRentalCourtsCourtInfo'
        type: array
      date:
        type: string
    type: object
info:
  contact: {}
  description: Line-Bot
  title: Heroku-Line-Bot
  version: "1.0"
paths:
  /badminton/activitys:
    get:
      description: 尚未截止的活動
      parameters:
      - description: 起始日期
        in: query
        name: from_date
        type: string
      - description: 結束日期
        in: query
        name: to_date
        type: string
      - description: 場館IDs
        in: query
        items:
          type: integer
        name: place_ids
        type: array
      - description: 球隊IDs
        in: query
        items:
          type: integer
        name: team_ids
        type: array
      - description: 分頁每頁資料量
        in: query
        name: page_size
        required: true
        type: integer
      - description: 分頁第幾頁，1開始
        in: query
        name: page_index
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 資料
          schema:
            allOf:
            - $ref: '#/definitions/resp.Base'
            - properties:
                data:
                  $ref: '#/definitions/resp.GetActivitys'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 活動列表
      tags:
      - Badminton
  /badminton/rental-courts:
    get:
      description: 租場狀況
      parameters:
      - default: "2013-08-02T00:00:00+08:00"
        description: 起始日期
        in: query
        name: from_date
        required: true
        type: string
      - default: "2013-08-02T00:00:00+08:00"
        description: 結束日期
        in: query
        name: to_date
        required: true
        type: string
      - description: 球隊id
        in: query
        name: team_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 資料
          schema:
            $ref: '#/definitions/resp.GetRentalCourts'
      security:
      - ApiKeyAuth: []
      summary: 租場狀況
      tags:
      - Badminton
    post:
      consumes:
      - application/json
      description: 新增租場
      parameters:
      - description: 參數
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/reqs.AddRentalCourt'
      produces:
      - application/json
      responses:
        "200":
          description: 資料
          schema:
            $ref: '#/definitions/resp.Base'
      security:
      - ApiKeyAuth: []
      summary: 新增租場
      tags:
      - Badminton
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
