apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hostpath
